"""
AUTO-GENERATED TRADING BOT
=========================
Strategy: Expert_MeanReversion_EURUSD_H1_458
Type: Mean Reversion
Generated: 2026-01-15 15:51:15
Source Genome ID: 303e24e0-aaeb-4587-ab85-ed27bcd4747f

DO NOT EDIT THIS FILE MANUALLY - IT IS AUTO-GENERATED
"""

import MetaTrader5 as mt5
import pandas as pd
import numpy as np
import talib
from datetime import datetime
import time
import logging
import sys, os

# Allow import from project root
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))))
from titan_system.factory.portfolio.portfolio_manager import PortfolioManager

logging.basicConfig(level=logging.INFO, format='%(asctime)s [BOT] %(message)s')
logger = logging.getLogger("Expert_MeanReversion_EURUSD_H1_458")

# === STRATEGY PARAMETERS ===
SYMBOL = "EURUSD"
TIMEFRAME = mt5.TIMEFRAME_H1
MAGIC_NUMBER = 999001
RISK_PERCENT = 0.014122741831072008
MAX_POSITIONS = 2

# Indicator Parameters
RSI_PERIOD = 13
RSI_OVERSOLD = 33
RSI_OVERBOUGHT = 69
BB_PERIOD = 20
BB_STD = 2.0

# Exit Parameters
TP_MULTIPLIER = 4.424158668273552
SL_ATR_MULT = 2.049294025594663

def analyze_market():
    """Analyze market and generate signals."""
    rates = mt5.copy_rates_from_pos(SYMBOL, TIMEFRAME, 0, 100)
    if rates is None or len(rates) < 30:
        return None
    
    df = pd.DataFrame(rates)
    close = df['close'].values
    high = df['high'].values
    low = df['low'].values
    
    # Calculate indicators
    df['RSI'] = talib.RSI(close, timeperiod=RSI_PERIOD)
    upper, middle, lower = talib.BBANDS(close, timeperiod=BB_PERIOD, nbdevup=BB_STD, nbdevdn=BB_STD)
    df['BB_upper'] = upper
    df['BB_lower'] = lower
    df['ATR'] = talib.ATR(high, low, close, timeperiod=14)
    
    curr = df.iloc[-1]
    
    # Entry logic (Mean Reversion)
    signal = None
    score = 0
    
    if curr['RSI'] < RSI_OVERSOLD and curr['close'] < curr['BB_lower']:
        signal = "BUY"
        score = 80
    elif curr['RSI'] > RSI_OVERBOUGHT and curr['close'] > curr['BB_upper']:
        signal = "SELL"
        score = 80
    
    if signal:
        return {
            'direction': signal,
            'score': score,
            'price': curr['close'],
            'atr': curr['ATR']
        }
    
    return None

def calculate_position_size(entry, sl):
    """Calculate position size using the centralized PortfolioManager."""
    pm = PortfolioManager()
    return pm.calculate_optimal_size("303e24e0-aaeb-4587-ab85-ed27bcd4747f", SYMBOL, entry, sl)

def execute_trade(signal):
    """Execute trade based on signal."""
    # Check if we already have max positions
    positions = mt5.positions_get(symbol=SYMBOL, magic=MAGIC_NUMBER)
    if positions and len(positions) >= MAX_POSITIONS:
        logger.info("Max positions reached")
        return False
    
    direction = signal['direction']
    price = signal['price']
    atr = signal['atr']
    
    # Calculate SL and TP
    if direction == "BUY":
        order_type = mt5.ORDER_TYPE_BUY
        sl = price - (atr * SL_ATR_MULT)
        tp = price + (atr * SL_ATR_MULT * TP_MULTIPLIER)
    else:
        order_type = mt5.ORDER_TYPE_SELL
        sl = price + (atr * SL_ATR_MULT)
        tp = price - (atr * SL_ATR_MULT * TP_MULTIPLIER)
    
    # Position size using PortfolioManager
    lot_size = calculate_position_size(price, sl)
    
    # Prepare order
    request = {
        "action": mt5.TRADE_ACTION_DEAL,
        "symbol": SYMBOL,
        "volume": lot_size,
        "type": order_type,
        "price": price,
        "sl": sl,
        "tp": tp,
        "magic": MAGIC_NUMBER,
        "comment": "Expert_MeanReversion",
        "type_time": mt5.ORDER_TIME_GTC,
        "type_filling": mt5.ORDER_FILLING_IOC,
    }
    
    result = mt5.order_send(request)
    
    if result.retcode == mt5.TRADE_RETCODE_DONE:
        logger.info(f"✅ Trade executed: {direction} {lot_size} lots @ {price:.5f}")
        logger.info(f"   SL: {sl:.5f}, TP: {tp:.5f}")
        return True
    else:
        logger.error(f"❌ Trade failed: {result.retcode} - {result.comment}")
        return False

def main():
    """Main bot loop."""
    logger.info("=" * 60)
    logger.info(f"Bot: Expert_MeanReversion_EURUSD_H1_458")
    logger.info(f"Symbol: {SYMBOL}, Magic: {MAGIC_NUMBER}")
    logger.info("=" * 60)
    
    if not mt5.initialize():
        logger.error("MT5 initialization failed")
        return
    
    logger.info("✅ MT5 connected")
    logger.info("🤖 Bot running...")
    
    try:
        while True:
            signal = analyze_market()
            
            if signal:
                logger.info(f"🎯 Signal detected: {signal['direction']} (Score: {signal['score']})")
                execute_trade(signal)
            
            time.sleep(60)  # Check every minute
            
    except KeyboardInterrupt:
        logger.info("Bot stopped by user")
    except Exception as e:
        logger.error(f"Error: {e}")
    finally:
        mt5.shutdown()

if __name__ == "__main__":
    main()
