"""
CODE COMPILER - Strategy Genome to Executable Bot
=================================================
Converts StrategyGenome format into executable Python trading bot code.

Process:
1. Load genome
2. Select appropriate template based on strategy type
3. Generate indicator calculation code
4. Generate entry/exit logic
5. Inject parameters
6. Save as executable .py file
7. Assign unique magic number

Output: Fully functional MT5 trading bot ready for deployment.
"""

import os
import json
from typing import Dict, Optional
from datetime import datetime
from pathlib import Path

import sys
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))

from titan_system.factory.strategy_genome import StrategyGenome
from titan_system.factory import factory_config as cfg


class CodeCompiler:
    """
    Compiles StrategyGenome into executable Python bot code.
    """
    
    def __init__(self, output_dir: str = None):
        """
        Initialize compiler.
        
        Args:
            output_dir: Directory to save generated bots (default: titan_system/strategies/autogen)
        """
        if output_dir is None:
            base_dir = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
            output_dir = os.path.join(base_dir, "strategies", "autogen")
        
        self.output_dir = output_dir
        Path(self.output_dir).mkdir(parents=True, exist_ok=True)
        
        self.magic_counter = cfg.MAGIC_NUMBER_START
    
    def compile_strategy(self, genome: StrategyGenome, magic_number: int = None) -> tuple[str, int]:
        """
        Compile genome into executable bot code.
        
        Args:
            genome: StrategyGenome to compile
            magic_number: Optional magic number (auto-assigned if None)
        
        Returns:
            Path to generated bot file
        """
        print(f"Compiling strategy: {genome.name}")
        
        # Assign magic number
        if magic_number is None:
            magic_number = self._get_next_magic_number()
        
        # Generate code based on strategy type
        if genome.type == StrategyGenome.MEAN_REVERSION:
            code = self._generate_mean_reversion_bot(genome, magic_number)
        elif genome.type == StrategyGenome.TREND_FOLLOWING:
            code = self._generate_trend_following_bot(genome, magic_number)
        elif genome.type == StrategyGenome.BREAKOUT:
            code = self._generate_breakout_bot(genome, magic_number)
        elif genome.type == StrategyGenome.SCALPING:
            code = self._generate_scalping_bot(genome, magic_number)
        elif genome.type == StrategyGenome.MOMENTUM:
            code = self._generate_momentum_bot(genome, magic_number)
        else:
            code = self._generate_generic_bot(genome, magic_number)
        
        # Save to file
        filename = f"autogen_{genome.id[:8]}_{genome.name.replace(' ', '_')}.py"
        filepath = os.path.join(self.output_dir, filename)
        
        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(code)
        
        print(f"✅ Generated: {filepath}")
        print(f"   Magic Number: {magic_number}")
        
        return filepath, magic_number
    
    def _get_next_magic_number(self) -> int:
        """Get next available magic number."""
        magic = self.magic_counter
        self.magic_counter += 1
        
        if self.magic_counter > cfg.MAGIC_NUMBER_END:
            self.magic_counter = cfg.MAGIC_NUMBER_START
        
        return magic
    
    # ==================== BOT GENERATORS ====================
    
    def _generate_mean_reversion_bot(self, genome: StrategyGenome, magic: int) -> str:
        """Generate mean reversion bot code."""
        # Extract parameters
        symbol = genome.symbols[0] if genome.symbols else "GOLD"
        tf = genome.timeframe
        risk_pct = genome.parameters.get('risk_per_trade', 0.01)
        max_positions = genome.parameters.get('max_positions', 2)
        
        # Indicators
        rsi_period = genome.indicators.get('RSI', {}).get('period', 14)
        rsi_oversold = genome.indicators.get('RSI', {}).get('oversold', 30)
        rsi_overbought = genome.indicators.get('RSI', {}).get('overbought', 70)
        
        bb_period = genome.indicators.get('BB', {}).get('period', 20)
        bb_std = genome.indicators.get('BB', {}).get('std', 2.0)
        
        # Exit rules
        tp_mult = genome.exit_rules.get('tp_mult', 2.0)
        sl_atr = genome.exit_rules.get('sl_atr', 1.5)
        
        code = f'''"""
AUTO-GENERATED TRADING BOT
=========================
Strategy: {genome.name}
Type: Mean Reversion
Generated: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
Source Genome ID: {genome.id}

DO NOT EDIT THIS FILE MANUALLY - IT IS AUTO-GENERATED
"""

import MetaTrader5 as mt5
import pandas as pd
import numpy as np
import talib
from datetime import datetime
import time
import logging
import sys, os

# Allow import from project root
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))))
from titan_system.factory.portfolio.portfolio_manager import PortfolioManager

logging.basicConfig(level=logging.INFO, format='%(asctime)s [BOT] %(message)s')
logger = logging.getLogger("{genome.name}")

# === STRATEGY PARAMETERS ===
SYMBOL = "{symbol}"
TIMEFRAME = mt5.TIMEFRAME_{tf}
MAGIC_NUMBER = {magic}
RISK_PERCENT = {risk_pct}
MAX_POSITIONS = {max_positions}

# Indicator Parameters
RSI_PERIOD = {rsi_period}
RSI_OVERSOLD = {rsi_oversold}
RSI_OVERBOUGHT = {rsi_overbought}
BB_PERIOD = {bb_period}
BB_STD = {bb_std}

# Exit Parameters
TP_MULTIPLIER = {tp_mult}
SL_ATR_MULT = {sl_atr}

def analyze_market():
    """Analyze market and generate signals."""
    rates = mt5.copy_rates_from_pos(SYMBOL, TIMEFRAME, 0, 100)
    if rates is None or len(rates) < {max(rsi_period, bb_period) + 10}:
        return None
    
    df = pd.DataFrame(rates)
    close = df['close'].values
    high = df['high'].values
    low = df['low'].values
    
    # Calculate indicators
    df['RSI'] = talib.RSI(close, timeperiod=RSI_PERIOD)
    upper, middle, lower = talib.BBANDS(close, timeperiod=BB_PERIOD, nbdevup=BB_STD, nbdevdn=BB_STD)
    df['BB_upper'] = upper
    df['BB_lower'] = lower
    df['ATR'] = talib.ATR(high, low, close, timeperiod=14)
    
    curr = df.iloc[-1]
    
    # Entry logic (Mean Reversion)
    signal = None
    score = 0
    
    if curr['RSI'] < RSI_OVERSOLD and curr['close'] < curr['BB_lower']:
        signal = "BUY"
        score = 80
    elif curr['RSI'] > RSI_OVERBOUGHT and curr['close'] > curr['BB_upper']:
        signal = "SELL"
        score = 80
    
    if signal:
        return {{
            'direction': signal,
            'score': score,
            'price': curr['close'],
            'atr': curr['ATR']
        }}
    
    return None

def calculate_position_size(entry, sl):
    """Calculate position size using the centralized PortfolioManager."""
    pm = PortfolioManager()
    return pm.calculate_optimal_size("{genome.id}", SYMBOL, entry, sl)

def execute_trade(signal):
    """Execute trade based on signal."""
    # Check if we already have max positions
    positions = mt5.positions_get(symbol=SYMBOL, magic=MAGIC_NUMBER)
    if positions and len(positions) >= MAX_POSITIONS:
        logger.info("Max positions reached")
        return False
    
    direction = signal['direction']
    price = signal['price']
    atr = signal['atr']
    
    # Calculate SL and TP
    if direction == "BUY":
        order_type = mt5.ORDER_TYPE_BUY
        sl = price - (atr * SL_ATR_MULT)
        tp = price + (atr * SL_ATR_MULT * TP_MULTIPLIER)
    else:
        order_type = mt5.ORDER_TYPE_SELL
        sl = price + (atr * SL_ATR_MULT)
        tp = price - (atr * SL_ATR_MULT * TP_MULTIPLIER)
    
    # Position size using PortfolioManager
    lot_size = calculate_position_size(price, sl)
    
    # Prepare order
    request = {{
        "action": mt5.TRADE_ACTION_DEAL,
        "symbol": SYMBOL,
        "volume": lot_size,
        "type": order_type,
        "price": price,
        "sl": sl,
        "tp": tp,
        "magic": MAGIC_NUMBER,
        "comment": "{genome.name[:20]}",
        "type_time": mt5.ORDER_TIME_GTC,
        "type_filling": mt5.ORDER_FILLING_IOC,
    }}
    
    result = mt5.order_send(request)
    
    if result.retcode == mt5.TRADE_RETCODE_DONE:
        logger.info(f"✅ Trade executed: {{direction}} {{lot_size}} lots @ {{price:.5f}}")
        logger.info(f"   SL: {{sl:.5f}}, TP: {{tp:.5f}}")
        return True
    else:
        logger.error(f"❌ Trade failed: {{result.retcode}} - {{result.comment}}")
        return False

def main():
    """Main bot loop."""
    logger.info("=" * 60)
    logger.info(f"Bot: {genome.name}")
    logger.info(f"Symbol: {{SYMBOL}}, Magic: {{MAGIC_NUMBER}}")
    logger.info("=" * 60)
    
    if not mt5.initialize():
        logger.error("MT5 initialization failed")
        return
    
    logger.info("✅ MT5 connected")
    logger.info("🤖 Bot running...")
    
    try:
        while True:
            signal = analyze_market()
            
            if signal:
                logger.info(f"🎯 Signal detected: {{signal['direction']}} (Score: {{signal['score']}})")
                execute_trade(signal)
            
            time.sleep(60)  # Check every minute
            
    except KeyboardInterrupt:
        logger.info("Bot stopped by user")
    except Exception as e:
        logger.error(f"Error: {{e}}")
    finally:
        mt5.shutdown()

if __name__ == "__main__":
    main()
'''
        return code
    
    def _generate_trend_following_bot(self, genome: StrategyGenome, magic: int) -> str:
        """Generate trend following bot code with full execution."""
        symbol = genome.symbols[0] if genome.symbols else "EURUSD"
        tf = genome.timeframe
        risk_pct = genome.parameters.get('risk_per_trade', 0.01)
        max_positions = genome.parameters.get('max_positions', 2)
        
        ema_fast = genome.indicators.get('EMA_fast', {}).get('period', 9)
        ema_slow = genome.indicators.get('EMA_slow', {}).get('period', 21)
        
        tp_mult = genome.exit_rules.get('tp_mult', 3.0)
        sl_atr = genome.exit_rules.get('sl_atr', 2.0)
        
        code = f'''"""
AUTO-GENERATED TREND FOLLOWING BOT
Generated: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
Strategy: {genome.name}
"""

import MetaTrader5 as mt5
import pandas as pd
import talib
import time
import logging
import sys, os

# Allow import from project root
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))))
from titan_system.factory.portfolio.portfolio_manager import PortfolioManager

logging.basicConfig(level=logging.INFO, format='%(asctime)s [BOT] %(message)s')
logger = logging.getLogger("{genome.name}")

SYMBOL = "{symbol}"
TIMEFRAME = mt5.TIMEFRAME_{tf}
MAGIC_NUMBER = {magic}
RISK_PERCENT = {risk_pct}
MAX_POSITIONS = {max_positions}

EMA_FAST = {ema_fast}
EMA_SLOW = {ema_slow}
TP_MULT = {tp_mult}
SL_ATR_MULT = {sl_atr}

def analyze_market():
    rates = mt5.copy_rates_from_pos(SYMBOL, TIMEFRAME, 0, 100)
    if rates is None: return None
    
    df = pd.DataFrame(rates)
    close = df['close'].values
    high = df['high'].values
    low = df['low'].values
    
    df['EMA_fast'] = talib.EMA(close, timeperiod=EMA_FAST)
    df['EMA_slow'] = talib.EMA(close, timeperiod=EMA_SLOW)
    df['ATR'] = talib.ATR(high, low, close, timeperiod=14)
    
    curr = df.iloc[-1]
    prev = df.iloc[-2]
    
    if prev['EMA_fast'] <= prev['EMA_slow'] and curr['EMA_fast'] > curr['EMA_slow']:
        return {{'direction': 'BUY', 'score': 85, 'price': curr['close'], 'atr': curr['ATR']}}
    elif prev['EMA_fast'] >= prev['EMA_slow'] and curr['EMA_fast'] < curr['EMA_slow']:
        return {{'direction': 'SELL', 'score': 85, 'price': curr['close'], 'atr': curr['ATR']}}
    
    return None

def calculate_position_size(entry, sl):
    pm = PortfolioManager()
    return pm.calculate_optimal_size("{genome.id}", SYMBOL, entry, sl)

def execute_trade(signal):
    positions = mt5.positions_get(symbol=SYMBOL, magic=MAGIC_NUMBER)
    if positions and len(positions) >= MAX_POSITIONS: return False
    
    direction = signal['direction']
    price = signal['price']
    atr = signal['atr']
    
    if direction == "BUY":
        order_type = mt5.ORDER_TYPE_BUY
        sl = price - (atr * SL_ATR_MULT)
        tp = price + (atr * SL_ATR_MULT * TP_MULT)
    else:
        order_type = mt5.ORDER_TYPE_SELL
        sl = price + (atr * SL_ATR_MULT)
        tp = price - (atr * SL_ATR_MULT * TP_MULT)
    
    lot_size = calculate_position_size(price, sl)
    
    request = {{
        "action": mt5.TRADE_ACTION_DEAL,
        "symbol": SYMBOL,
        "volume": lot_size,
        "type": order_type,
        "price": price,
        "sl": sl,
        "tp": tp,
        "magic": MAGIC_NUMBER,
        "comment": "{genome.name[:20]}",
        "type_time": mt5.ORDER_TIME_GTC,
        "type_filling": mt5.ORDER_FILLING_IOC,
    }}
    
    result = mt5.order_send(request)
    if result.retcode == mt5.TRADE_RETCODE_DONE:
        logger.info(f"✅ Trade executed: {{direction}} {{lot_size}} lots @ {{price:.5f}}")
        return True
    return False

def main():
    if not mt5.initialize(): return
    logger.info("✅ MT5 connected | Bot: {genome.name}")
    try:
        while True:
            signal = analyze_market()
            if signal:
                logger.info(f"🎯 Signal: {{signal['direction']}}")
                execute_trade(signal)
            time.sleep(60)
    finally:
        mt5.shutdown()

if __name__ == "__main__":
    main()
'''
        return code
        return code
    
    def _generate_scalping_bot(self, genome: StrategyGenome, magic: int) -> str:
        """Generate high-frequency scalping bot code with divergence logic."""
        symbol = genome.symbols[0] if genome.symbols else "GOLD"
        tf = genome.timeframe
        risk_pct = genome.parameters.get('risk_per_trade', 0.005) # Lower risk for scalp
        
        rsi_period = genome.indicators.get('RSI', {}).get('period', 7)
        tp_mult = genome.exit_rules.get('tp_mult', 1.5)
        sl_atr = genome.exit_rules.get('sl_atr', 1.0)
        
        code = f'''"""
AUTO-GENERATED SCALPING BOT
Strategy: {genome.name}
Generated: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
"""

import MetaTrader5 as mt5
import pandas as pd
import talib
import time
import logging

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("{genome.name}")

SYMBOL = "{symbol}"
TIMEFRAME = mt5.TIMEFRAME_{tf}
MAGIC_NUMBER = {magic}
RISK_PERCENT = {risk_pct}

# Indicators
RSI_PERIOD = {rsi_period}
TP_MULT = {tp_mult}
SL_ATR = {sl_atr}

def analyze_market():
    rates = mt5.copy_rates_from_pos(SYMBOL, TIMEFRAME, 0, 100)
    if rates is None or len(rates) < 50: return None
    
    df = pd.DataFrame(rates)
    close = df['close'].values
    high = df['high'].values
    low = df['low'].values
    
    df['RSI'] = talib.RSI(close, timeperiod=RSI_PERIOD)
    macd, macdsignal, macdhist = talib.MACD(close)
    df['MACD_hist'] = macdhist
    df['ATR'] = talib.ATR(high, low, close, timeperiod=14)
    
    curr = df.iloc[-1]
    prev = df.iloc[-2]
    
    # Scalp Logic: RSI extreme + Momentum shift
    if curr['RSI'] < 25 and curr['MACD_hist'] > prev['MACD_hist']:
        return {{'direction': 'BUY', 'price': curr['close'], 'atr': curr['ATR']}}
    elif curr['RSI'] > 75 and curr['MACD_hist'] < prev['MACD_hist']:
        return {{'direction': 'SELL', 'price': curr['close'], 'atr': curr['ATR']}}
    
    return None

def execute_trade(signal):
    # Safety: Check if already in position
    pos = mt5.positions_get(symbol=SYMBOL, magic=MAGIC_NUMBER)
    if pos: return # One at a time for scalper safety
    
    # Calculate SL/TP
    price = signal['price']
    atr = signal['atr']
    sl_dist = atr * SL_ATR
    
    if signal['direction'] == 'BUY':
        sl = price - sl_dist
        tp = price + (sl_dist * TP_MULT)
        order_type = mt5.ORDER_TYPE_BUY
    else:
        sl = price + sl_dist
        tp = price - (sl_dist * TP_MULT)
        order_type = mt5.ORDER_TYPE_SELL
        
    # Fixed risk sizing (No Martingale)
    acc = mt5.account_info()
    lot = (acc.equity * RISK_PERCENT) / (sl_dist * 100000) # Simple lot calc
    lot = max(0.01, round(lot, 2))
    
    request = {{
        "action": mt5.TRADE_ACTION_DEAL,
        "symbol": SYMBOL,
        "volume": lot,
        "type": order_type,
        "price": price,
        "sl": sl,
        "tp": tp,
        "magic": MAGIC_NUMBER,
        "comment": "ExpertScalp",
        "type_time": mt5.ORDER_TIME_GTC,
        "type_filling": mt5.ORDER_FILLING_IOC,
    }}
    mt5.order_send(request)

def main():
    if not mt5.initialize(): return
    while True:
        sig = analyze_market()
        if sig: execute_trade(sig)
        time.sleep(30) # Fast check for M5/M1

if __name__ == "__main__":
    main()
'''
        return code

    def _generate_momentum_bot(self, genome: StrategyGenome, magic: int) -> str:
        """Generate momentum following bot code with full execution."""
        symbol = genome.symbols[0] if genome.symbols else "GOLD"
        tf = genome.timeframe
        risk_pct = genome.parameters.get('risk_per_trade', 0.01)
        max_positions = genome.parameters.get('max_positions', 2)
        
        tp_mult = genome.exit_rules.get('tp_mult', 2.5)
        sl_atr = genome.exit_rules.get('sl_atr', 1.5)
        
        code = f'''"""
AUTO-GENERATED MOMENTUM BOT
Strategy: {genome.name}
Generated: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
"""

import MetaTrader5 as mt5
import pandas as pd
import talib
import time
import logging
import sys, os

# Allow import from project root
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))))
from titan_system.factory.portfolio.portfolio_manager import PortfolioManager

logging.basicConfig(level=logging.INFO, format='%(asctime)s [BOT] %(message)s')
logger = logging.getLogger("{genome.name}")

SYMBOL = "{symbol}"
TIMEFRAME = mt5.TIMEFRAME_{tf}
MAGIC_NUMBER = {magic}
RISK_PERCENT = {risk_pct}
MAX_POSITIONS = {max_positions}

TP_MULT = {tp_mult}
SL_ATR_MULT = {sl_atr}

def analyze_market():
    rates = mt5.copy_rates_from_pos(SYMBOL, TIMEFRAME, 0, 50)
    if rates is None or len(rates) < 20: return None
    
    df = pd.DataFrame(rates)
    df['Momentum'] = df['close'] - df['close'].shift(10)
    df['ATR'] = talib.ATR(df['high'].values, df['low'].values, df['close'].values, timeperiod=14)
    
    curr = df.iloc[-1]
    if curr['Momentum'] > 0:
        return {{'direction': 'BUY', 'price': curr['close'], 'atr': curr['ATR']}}
    elif curr['Momentum'] < 0:
        return {{'direction': 'SELL', 'price': curr['close'], 'atr': curr['ATR']}}
    return None

def calculate_position_size(entry, sl):
    pm = PortfolioManager()
    return pm.calculate_optimal_size("{genome.id}", SYMBOL, entry, sl)

def execute_trade(signal):
    positions = mt5.positions_get(symbol=SYMBOL, magic=MAGIC_NUMBER)
    if positions and len(positions) >= MAX_POSITIONS: return False
    
    direction = signal['direction']
    price = signal['price']
    atr = signal['atr']
    
    if direction == "BUY":
        order_type = mt5.ORDER_TYPE_BUY
        sl = price - (atr * SL_ATR_MULT)
        tp = price + (atr * SL_ATR_MULT * TP_MULT)
    else:
        order_type = mt5.ORDER_TYPE_SELL
        sl = price + (atr * SL_ATR_MULT)
        tp = price - (atr * SL_ATR_MULT * TP_MULT)
    
    lot_size = calculate_position_size(price, sl)
    
    request = {{
        "action": mt5.TRADE_ACTION_DEAL,
        "symbol": SYMBOL,
        "volume": lot_size,
        "type": order_type,
        "price": price,
        "sl": sl,
        "tp": tp,
        "magic": MAGIC_NUMBER,
        "comment": "{genome.name[:20]}",
        "type_time": mt5.ORDER_TIME_GTC,
        "type_filling": mt5.ORDER_FILLING_IOC,
    }}
    
    result = mt5.order_send(request)
    if result and result.retcode == mt5.TRADE_RETCODE_DONE:
        logger.info(f"✅ Momentum Trade: {{direction}} {{lot_size}} lots")
        return True
    return False

def main():
    if not mt5.initialize(): return
    logger.info("✅ MT5 Connected | Bot: {genome.name}")
    try:
        while True:
            sig = analyze_market()
            if sig:
                logger.info(f"🎯 Momentum Signal: {{sig['direction']}}")
                execute_trade(sig)
            time.sleep(60)
    finally:
        mt5.shutdown()

if __name__ == "__main__":
    main()
'''
    def _generate_breakout_bot(self, genome: StrategyGenome, magic: int) -> str:
        """Generate institutional breakout bot code."""
        code = f'''"""
TITAN OS :: BREAKOUT BOT :: {genome.name}
Generated: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
Strategy ID: {genome.id}
Magic Number: {magic}
"""

import MetaTrader5 as mt5
import pandas as pd
import numpy as np
import time
import talib
from datetime import datetime

# --- CONFIG ---
SYMBOL = "{genome.symbols[0]}"
TIMEFRAME = mt5.TIMEFRAME_{genome.timeframe} if hasattr(mt5, "TIMEFRAME_{genome.timeframe}") else mt5.TIMEFRAME_H1
MAGIC = {magic}
LOT_SIZE = {genome.parameters.get('lot_size', 0.1)}
SL_ATR = {genome.exit_rules.get('sl_atr', 1.5)}
TP_MULT = {genome.exit_rules.get('tp_mult', 2.0)}

# --- INDICATOR PARAMS ---
{self._format_params_as_constants(genome)}

def get_data(symbol, timeframe, n=100):
    rates = mt5.copy_rates_from_pos(symbol, timeframe, 0, n)
    if rates is None: return None
    df = pd.DataFrame(rates)
    df['time'] = pd.to_datetime(df['time'], unit='s')
    return df

def calculate_vlatility(df):
    return talib.ATR(df['high'], df['low'], df['close'], timeperiod=14).iloc[-1]

def get_signal(df):
    close = df['close'].values
    high = df['high'].values
    low = df['low'].values
    
    # Breakout Logic: BB or Keltner or High/Low
    upper, middle, lower = talib.BBANDS(close, timeperiod=20, nbdevup=2.0, nbdevdn=2.0)
    
    if close[-1] > upper[-1] and close[-2] <= upper[-2]:
        return 1 # BULLISH BREAKOUT
    if close[-1] < lower[-1] and close[-2] >= lower[-2]:
        return -1 # BEARISH BREAKOUT
        
    return 0

def execute_trade(direction, sl_pips, tp_pips):
    price = mt5.symbol_info_tick(SYMBOL).ask if direction == 1 else mt5.symbol_info_tick(SYMBOL).bid
    point = mt5.symbol_info(SYMBOL).point
    
    request = {{
        "action": mt5.TRADE_ACTION_DEAL,
        "symbol": SYMBOL,
        "volume": LOT_SIZE,
        "type": mt5.ORDER_TYPE_BUY if direction == 1 else mt5.ORDER_TYPE_SELL,
        "price": price,
        "sl": price - (sl_pips * point) if direction == 1 else price + (sl_pips * point),
        "tp": price + (tp_pips * point) if direction == 1 else price - (tp_pips * point),
        "magic": MAGIC,
        "comment": "Titan OS Breakout",
        "type_time": mt5.ORDER_TIME_GTC,
        "type_filling": mt5.ORDER_FILLING_IOC,
    }}
    return mt5.order_send(request)

def main():
    if not mt5.initialize(): return
    print(f"🚀 Breakout Bot {{MAGIC}} Active on {{SYMBOL}}")
    
    while True:
        try:
            df = get_data(SYMBOL, TIMEFRAME)
            if df is not None:
                # Check for existing positions
                pos = mt5.positions_get(symbol=SYMBOL, magic=MAGIC)
                if not pos:
                    signal = get_signal(df)
                    if signal != 0:
                        atr = calculate_vlatility(df)
                        sl_pips = (atr * SL_ATR) / mt5.symbol_info(SYMBOL).point
                        tp_pips = sl_pips * TP_MULT
                        res = execute_trade(signal, sl_pips, tp_pips)
                        print(f"Trade Result: {{res.comment}}")
            time.sleep(60)
        except Exception as e:
            print(f"Error: {{e}}")
            time.sleep(10)

if __name__ == "__main__":
    main()
'''
        return code

    def _format_params_as_constants(self, genome):
        params_str = ""
        for name, val in genome.indicators.items():
            for p_name, p_val in val.items():
                params_str += f"{name}_{p_name} = {p_val}\\n"
        return params_str

    def _generate_generic_bot(self, genome: StrategyGenome, magic: int) -> str:
        """Generate generic bot for unsupported types."""
        code = f'''"""
AUTO-GENERATED BOT (Generic Template)
Generated: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
Strategy: {genome.name}
Type: {genome.type}
"""

# TODO: Implement custom logic for {genome.type}
print("Generic bot template - customize for your strategy type")
'''
        return code


if __name__ == "__main__":
    from titan_system.factory.strategy_genome import StrategyTemplates
    
    print("=" * 60)
    print("CODE COMPILER - Demo")
    print("=" * 60)
    
    compiler = CodeCompiler()
    
    # Test 1: Mean Reversion
    genome_mr = StrategyTemplates.rsi_mean_reversion("GOLD", "M15")
    print("\n1. Compiling Mean Reversion Strategy...")
    filepath = compiler.compile_strategy(genome_mr)
    print(f"   Saved to: {filepath}")
    
    # Test 2: Trend Following
    genome_trend = StrategyTemplates.ema_crossover_trend("EURUSD", "H1")
    print("\n2. Compiling Trend Following Strategy...")
    filepath = compiler.compile_strategy(genome_trend)
    print(f"   Saved to: {filepath}")
    
    print("\n✅ Code compilation demo complete")
    print(f"Generated bots saved in: {compiler.output_dir}")
