import pandas as pd
import numpy as np
import ta
import json
import os
import sys

# Go up one level to import core
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))

from core.mt5_interface import MT5Interface
import MetaTrader5 as mt5

class DeepBacktester:
    def __init__(self, symbol, brain_file):
        self.symbol = symbol
        # Brain file logic: check data folder first
        self.brain_file = os.path.join('data', brain_file) if not os.path.exists(brain_file) else brain_file
        self.params = self._load_brain()
        self.df = None
        
    def _load_brain(self):
        if not os.path.exists(self.brain_file):
            print(f"❌ Brain file {self.brain_file} not found. Using defaults.")
            return {'sma_fast': 20, 'sma_slow': 50, 'rsi_period': 14}
            
        with open(self.brain_file, 'r') as f:
            data = json.load(f)
            return data.get('genes', data)

    def fetch_data(self, candles=5000):
        interface = MT5Interface()
        if interface.start():
            print(f"📥 Fetching {candles} candles for {self.symbol}...")
            self.df = interface.get_closes(self.symbol, mt5.TIMEFRAME_H1, num_candles=candles)
            interface.shutdown()
        return self.df is not None

    def run(self):
        if self.df is None: return
        
        data = self.df.copy()
        
        # 1. Indicators
        p = self.params
        data['fast'] = ta.trend.sma_indicator(data['close'], window=int(p['sma_fast']))
        data['slow'] = ta.trend.sma_indicator(data['close'], window=int(p['sma_slow']))
        # data['rsi'] = ta.momentum.rsi(data['close'], window=int(p['rsi_period']))
        
        # 2. Vectorized Signals
        data['signal'] = 0
        data.loc[data['fast'] > data['slow'], 'signal'] = 1 # Long
        data.loc[data['fast'] < data['slow'], 'signal'] = -1 # Short
        
        # 3. Returns & Costs
        SPREAD_COST = 0.00015 # 1.5 pips cost per trade
        
        data['market_return'] = data['close'].pct_change()
        data['trade_executed'] = data['signal'].diff().abs().fillna(0)
        data['cost'] = data['trade_executed'] * SPREAD_COST
        
        # Strategy Return = (Signal(t-1) * MarketReturn(t)) - Costs(t)
        # Note: We pay cost when we change position
        data['strategy_return'] = (data['signal'].shift(1) * data['market_return']) - data['cost']
        
        # 4. Metrics
        total_return = data['strategy_return'].sum() * 100
        trades = data['trade_executed'].sum()
        
        # Win Rate (Approximate by days/candles)
        winning_candles = len(data[data['strategy_return'] > 0])
        total_candles = len(data) # Not exactly trades, but directional accuracy
        
        print("\n📊 BACKTEST RESULTS (With Spread Costs)")
        print(f"Strategy: SMA {p['sma_fast']} / {p['sma_slow']} (Generated by AI)")
        print("-" * 40)
        print(f"Total Trades:      {int(trades)}")
        print(f"Net Return:        {total_return:.2f}%")
        print(f"Total Cost Paid:   {(data['cost'].sum() * 100):.2f}%")
        print("-" * 40)
        
        if total_return < 0:
            print("⚠️ WARNING: Strategy is LOSING money after costs.")
            print("   Action: Recommended to re-train AI with cost-aware optimizer.")
        else:
            print("✅ Strategy is PROFITABLE.")

if __name__ == "__main__":
    tester = DeepBacktester("EURUSD", "brain_EURUSD.json")
    if tester.fetch_data():
        tester.run()
