"""
Macro Companion Report Generator.
Translates institutional trading plans into plain English for non-finance audiences.
Logic: Take the CSV generated by weekly_plan_generator.py and create a narrative report.
"""

import pandas as pd
from datetime import datetime
import glob
import os

def generate_companion_report(csv_path=None):
    if csv_path is None:
        # Get the latest weekly plan CSV
        csv_files = glob.glob('WEEKLY_TRADING_PLAN_*.csv')
        if not csv_files:
            print("No trading plan CSV found.")
            return
        csv_path = max(csv_files, key=os.path.getctime)
    
    df = pd.read_csv(csv_path)
    
    report_path = f"analysis/MACRO_COMPANION_{datetime.now().strftime('%Y%m%d')}.md"
    os.makedirs('analysis', exist_ok=True)
    
    with open(report_path, 'w', encoding='utf-8') as f:
        f.write(f"# 🏦 Weekly Trading Plan: Plain English Companion\n")
        f.write(f"**Date:** {datetime.now().strftime('%Y-%m-%d')}\n\n")
        f.write("> This report translates technical market signals into logical cause-and-effect explanations. Use this to understand the 'why' behind our trading focus.\n\n")
        
        # Group by Asset Class
        asset_classes = df['Asset Class'].unique()
        
        for ac in asset_classes:
            f.write(f"## 📊 Asset Class: {ac}\n")
            ac_df = df[df['Asset Class'] == ac]
            
            # Summary of direction
            bullish_count = len(ac_df[ac_df['Focus'] == 'Long'])
            bearish_count = len(ac_df[ac_df['Focus'] == 'Short'])
            neutral_count = len(ac_df[ac_df['Focus'] == 'Stand Aside'])
            
            if bullish_count > bearish_count:
                direction = "leaning toward a positive (buying) outlook"
            elif bearish_count > bullish_count:
                direction = "leaning toward a negative (selling) outlook"
            else:
                direction = "currently in a state of uncertainty or waiting"
            
            f.write(f"**Market Leaning:** The {ac} market is {direction}.\n\n")
            
            # High Risks / Crowding
            crowded = ac_df[ac_df['Notes'].str.contains('Extreme', na=False)]
            if not crowded.empty:
                f.write(f"⚠️ **High Risk & Crowding:**\n")
                for _, row in crowded.iterrows():
                    f.write(f"- **{row['Instrument']}**: {row['Notes']}. This means too many people are already on one side of the boat; a sudden move in the opposite direction could happen fast.\n")
                f.write("\n")
            
            # Where Patience is Required
            patience = ac_df[ac_df['Focus'] == 'Stand Aside']
            if not patience.empty:
                f.write(f"⏳ **Patience Required:**\n")
                f.write(f"We are waiting for clearer signals in: {', '.join(patience['Instrument'].tolist())}. There is no clear trend or logical reason to risk money here right now.\n\n")
            
            # Where Not to Trade
            no_trade = ac_df[ac_df['Risk Guidance'] == 'Reduced']
            if not no_trade.empty:
                f.write(f"🛑 **Where NOT to Trade:**\n")
                f.write(f"Avoid aggressive positions in: {', '.join(no_trade['Instrument'].tolist())}. The environment is currently 'Uncertain' or 'Range-bound', making it easy to lose money on small, random price movements.\n\n")
            
            f.write("---\n\n")
            
        f.write("## 🎓 Key Concepts in This Plan\n\n")
        f.write("- **Net Score**: A simple way we rank how many positive reasons we have to trade. Higher is better for buying, lower better for selling.\n")
        f.write("- **Positioning Extreme**: When almost everyone trades the same way, the trade becomes 'fragile' and prone to reversing.\n")
        f.write("- **Seasonality**: Historical proof that certain months usually behave a certain way for specific assets.\n")
        f.write("- **MTF Alignment**: Making sure the short-term and long-term trends agree before we commit real capital.\n")

    print(f"✅ COMPANION REPORT GENERATED: {report_path}")
    return report_path

if __name__ == "__main__":
    generate_companion_report()
